matrix:
  include:
  - language: node_js
    node_js: 8
    script:
    - yarn && yarn lint && yarn test && cd reader-sdk-react-native-quickstart && yarn
      && yarn lint && cd ..
  - language: android
    sudo: false
    jdk: openjdk8
    os:
    - linux
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.yarn-cache"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - extra-google-google_play_services
    install:
    - nvm install 8
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd reader-sdk-react-native-quickstart
    - yarn
    script:
    - node ./node_modules/jetifier/index.js
    - cd android
    - "./gradlew clean build -PSQUARE_READER_SDK_APPLICATION_ID=$SQUARE_READER_SDK_APPLICATION_ID
      -PSQUARE_READER_SDK_REPOSITORY_PASSWORD=$SQUARE_READER_SDK_REPOSITORY_PASSWORD
      -x :react-native-camera-kit:lint"
  - language: objective-c
    os: osx
    osx_image: xcode11.1
    node_js:
    - 10.16.3
    cache:
      directories:
      - "$HOME/.yarn-cache"
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd reader-sdk-react-native-quickstart
    - yarn
    - cd ios && ruby <(curl https://connect.squareup.com/readersdk-installer) install
      --app-id $SQUARE_READER_SDK_APPLICATION_ID --repo-password $SQUARE_READER_SDK_REPOSITORY_PASSWORD
      --version 1.3.3 > /dev/null
    script:
    - xcodebuild -workspace RNReaderSDKSample.xcworkspace -configuration Debug -scheme
      RNReaderSDKSample -destination "platform=iOS Simulator,OS=13.1,name=iPhone 11"
      -derivedDataPath build/RNReaderSDKSample -quiet
notifications:
  slack:
    on_failure: change
    on_success: change
    template:
    - "@oncall Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
    secure: QVIpHUO1VjY/70oH2JAmyw7okQHlh2d2o/yBaKU8jlHO9B0Ea3E+oKYeN2F0yLNr/bD2MDnUHVPzO2e5+u2Ap6gYkIwXYGWdcp4jqY/yzWXu6zt/jw1bqFVB+ooaikvvsZlBwE86Wi4n06/uCkGpxEkqrv/Aj1FY84vGV7WjpXWjcGBi3ZgzqorEXdfsDSiKIVEXm2vvwlRIxSL4fqp0Wu83VKySnHv/A+YdvrIMA74miAXBlFLl7g40VcXN2x5QL+QvSeKLWg10qdUon7n+ShiW8DenWM/b1rPD1yp+feWxtBtzD6by4xQkVvUaNf7nTySMfikSnHTHuh2IdHRfDsmaiVjLm48JAi/DBVgcRG15sB0qVgXAAW1b/FAt2i2cMgIBksclRiBsLZnOj81Z2+FUyM5DnzUrnrxPfXqLHFRqID1KWOGq1I/1KoSRuzcqXAP6hAFthGmcjCnuZQjAw7LlCGbUVZ6M+8LEGkyZYQ6WET4FWkhTFec7m7bUGtxR78SvDaNvKr8s2zDtg6zTbCFDfsGm18kapx+N2ChKai7B/U8gcNGLCDyWsGMlO5OFxJXYfplzVDwiheiXjR9jQf+9XXsVH0uJSOutFaVXmq4dxS0YIXZgrc1yebx7eBCcJ247X1mOjwn3H7bwMC/2gVYb9FatMcGMDDzVK2svfFU=
